name: Build Release

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Branch to run the workflow on"
                required: true
                default: "gh-actions"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Install archive tools
              run: sudo apt install zip

            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.branch }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

			- name: Set env
     		  run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: Install dependencies
              run: yarn install

            - name: Build release
              run: yarn run build

			- name: Update tag ref
        	  uses: EndBug/latest-tag@latest
        	  with:
          		tag-name: ${{ github.ref_name }}

			- name: Bundle files
        	  run: |
          		mkdir -p ./temp/icarus
          		cp ./{LICENSE,README.md,fxmanifest.lua,config.lua,wrapper.lua} ./temp/icarus
          		cp -r ./dist ./temp/icarus
          		cd ./temp && zip -r ../Icarus.zip ./icarus

        	- name: Create Release
        	  uses: "marvinpinto/action-automatic-releases@v1.2.1"
              id: auto_release
        	  with:
          		repo_token: "${{ secrets.GITHUB_TOKEN }}"
          		title: ${{ env.RELEASE_VERSION }}
          		prerelease: false
          		files: dolu_tool.zip

			env:
          		CI: false
          		GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}